# Answer to Question on Functions

In [75]:
def overtime_pay():
    y=int(input("How many hours did you work this week?\n"))
    z=int(input("What is your base salary for this week?\n"))
    if y == 40 and z == 1800:
        print("You did not work overtime this week, your salary is $", z)
    elif y < 40:
        u = y*45
        print ("You worked for less than 40 hours this week, your salary is $", u)
    elif y > 40:
        u = (y-40)*50
        w = u + z
        print ("You worked overtime this week, your overtime pay is $", u)
        print ("Your total salary is $", w)


In [76]:
overtime_pay()

How many hours did you work this week?
40
What is your base salary for this week?
1800
You did not work overtime this week, your salary is $ 1800


In [77]:
overtime_pay()

How many hours did you work this week?
60
What is your base salary for this week?
1800
You worked overtime this week, your overtime pay is $ 1000
Your total salary is $ 2800


In [78]:
overtime_pay()

How many hours did you work this week?
32
What is your base salary for this week?
1800
You worked for less than 40 hours this week, your salary is $ 1440


# Answer to Question on List

In [73]:
try:
    
    mylist1 =[float(x) for x in input("Enter 10 float numbers separated by a comma in order here :\n").split(",")]
    if len(mylist1) < 10:
        print("Please enter up to 10 float numbers")
    elif len(mylist1) > 10:
        print("Please enter only 10 float numbers")
    elif len(mylist1) == 10:
        flag = 0
        if(mylist1 == sorted(mylist1)):
            flag = 1
        if (flag) :
            mylist2= [x for x in mylist1]
            mylist2.sort(reverse=True)
            print("Your list is in ascending order.\nHere is your list descending order:\n mylist2=" ,mylist2)
        else:
            print ("Numbers entered are not in ascending order")
            mylist1.sort()
            print("This is your list in ascending order\n", mylist1)
        

except:
    print("Your input does not match the above stated request. Please read the intructions and try again.")

Enter 10 float numbers separated by a comma in order here :
1,2,3,g,h,h,r,d
Your input does not match the above stated request. Please read the intructions and try again.


# Answer to Question on Dictionary

### Creating Dictionary

In [114]:
my_dict1={"School":"MTSU", "Textbooks":"14", "Level":"Elementary", "Hobby":"Dancing", "Height":"4.5inch", "Food":"Amala"}
print(my_dict1)

{'School': 'MTSU', 'Textbooks': '14', 'Level': 'Elementary', 'Hobby': 'Dancing', 'Height': '4.5inch', 'Food': 'Amala'}


### Updating Dictionary

In [115]:
my_dict1.update(School="FUTMinna", Hobby= "Reading" , Food="Spaghetti",)
print(my_dict1)

{'School': 'FUTMinna', 'Textbooks': '14', 'Level': 'Elementary', 'Hobby': 'Reading', 'Height': '4.5inch', 'Food': 'Spaghetti'}


### Adding New Key-Value Pairs

In [116]:
my_dict1["Location"]= "Nigeria"
my_dict1["Is_graduated"]= "Yes"
print(my_dict1)

{'School': 'FUTMinna', 'Textbooks': '14', 'Level': 'Elementary', 'Hobby': 'Reading', 'Height': '4.5inch', 'Food': 'Spaghetti', 'Location': 'Nigeria', 'Is_graduated': 'Yes'}


### Removing/Deleting Key-Value Pairs

In [117]:
my_dict1.pop("Hobby", None)
my_dict1.popitem()
print(my_dict1)

{'School': 'FUTMinna', 'Textbooks': '14', 'Level': 'Elementary', 'Height': '4.5inch', 'Food': 'Spaghetti', 'Location': 'Nigeria'}


# Answer to Question on Numpy

In [118]:
import numpy as np

### Creating Myarray1

In [144]:
myarray1= np.ones((20,11))
print (myarray1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Scalar Multiplication

In [145]:
a = 0.5
np.multiply(myarray1, a)

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.

### Updating Array

In [142]:
myarray1[5] = 10.5
myarray1[6] = 11.5
myarray1[:,0] = 9.5
print(myarray1)

[[ 9.5  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1. ]
 [ 9.5  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1. ]
 [ 9.5  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1. ]
 [ 9.5  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1. ]
 [ 9.5  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1. ]
 [ 9.5 10.5 10.5 10.5 10.5 10.5 10.5 10.5 10.5 10.5 10.5 10.5 10.5 10.5
  10.5 10.5 10.5 10.5 10.5 10.5]
 [ 9.5 11.5 11.5 11.5 11.5 11.5 11.5 11.5 11.5 11.5 11.5 11.5 11.5 11.5
  11.5 11.5 11.5 11.5 11.5 11.5]
 [ 9.5  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1. ]
 [ 9.5  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1. ]
 [ 9.5  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  

### Slicing Myarray1

In [147]:
print (myarray1[4:10])

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [149]:
print (myarray1[5:8])

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Merging 

In [160]:
a6= myarray1[:,5]
a8= myarray1[:,7]
print (np.hstack((a6,a8)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [161]:
a5= myarray1[:,4]
a10= myarray1[:,9]
print (np.vstack((a5,a10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
